//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRIER_ACTION
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public string Person_in_charge { get; set; }
        public string Phone_number { get; set; }
        public string Email { get; set; }
        public string LCC_Fee { get; set; }
        public string Note { get; set; }
    
        public virtual CARRIER CARRIER { get; set; }
    }
}
