//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public int MessageID { get; set; }
        public string Username { get; set; }
        public string MessageText { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual tbl_TAI_KHOAN tbl_TAI_KHOAN { get; set; }
    }
}
