//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGENT> AGENTs { get; set; }
        public virtual DbSet<AGENT_ACTION> AGENT_ACTION { get; set; }
        public virtual DbSet<BL_TYPE> BL_TYPE { get; set; }
        public virtual DbSet<CARRIER> CARRIERs { get; set; }
        public virtual DbSet<CARRIER_ACTION> CARRIER_ACTION { get; set; }
        public virtual DbSet<ChatMessage> ChatMessages { get; set; }
        public virtual DbSet<CPORT> CPORTs { get; set; }
        public virtual DbSet<CURRENCY> CURRENCies { get; set; }
        public virtual DbSet<FEE> FEEs { get; set; }
        public virtual DbSet<GOODS_TYPE> GOODS_TYPE { get; set; }
        public virtual DbSet<INVOICE_TYPE> INVOICE_TYPE { get; set; }
        public virtual DbSet<KINDOFPACKAGE> KINDOFPACKAGES { get; set; }
        public virtual DbSet<MODE> MODEs { get; set; }
        public virtual DbSet<Quotation> Quotations { get; set; }
        public virtual DbSet<Quotations_Charges> Quotations_Charges { get; set; }
        public virtual DbSet<SOURSE> SOURSEs { get; set; }
        public virtual DbSet<SUP_TYPE> SUP_TYPE { get; set; }
        public virtual DbSet<tbl_CHARGES> tbl_CHARGES { get; set; }
        public virtual DbSet<tbl_CNEE> tbl_CNEE { get; set; }
        public virtual DbSet<tbl_CNEE_ADD> tbl_CNEE_ADD { get; set; }
        public virtual DbSet<tbl_COM> tbl_COM { get; set; }
        public virtual DbSet<tbl_CONTH> tbl_CONTH { get; set; }
        public virtual DbSet<tbl_CUSTOMER> tbl_CUSTOMER { get; set; }
        public virtual DbSet<tbl_DELIVERY_CONTH> tbl_DELIVERY_CONTH { get; set; }
        public virtual DbSet<tbl_DELIVERYPFROOF> tbl_DELIVERYPFROOF { get; set; }
        public virtual DbSet<tbl_DEPARTMENT> tbl_DEPARTMENT { get; set; }
        public virtual DbSet<tbl_HBL> tbl_HBL { get; set; }
        public virtual DbSet<tbl_HSCODE> tbl_HSCODE { get; set; }
        public virtual DbSet<tbl_INVOICE> tbl_INVOICE { get; set; }
        public virtual DbSet<tbl_JOB> tbl_JOB { get; set; }
        public virtual DbSet<tbl_LOG> tbl_LOG { get; set; }
        public virtual DbSet<tbl_MESSAGES> tbl_MESSAGES { get; set; }
        public virtual DbSet<tbl_SCUSTOMER> tbl_SCUSTOMER { get; set; }
        public virtual DbSet<tbl_SCUSTOMER_RELATIONSHIP> tbl_SCUSTOMER_RELATIONSHIP { get; set; }
        public virtual DbSet<tbl_SHIPPER> tbl_SHIPPER { get; set; }
        public virtual DbSet<tbl_STAFF> tbl_STAFF { get; set; }
        public virtual DbSet<tbl_SUPPLIER> tbl_SUPPLIER { get; set; }
        public virtual DbSet<tbl_SUPPLIER_ACTION> tbl_SUPPLIER_ACTION { get; set; }
        public virtual DbSet<tbl_TAI_KHOAN> tbl_TAI_KHOAN { get; set; }
        public virtual DbSet<tbl_TAI_KHOAN_MESSAGES> tbl_TAI_KHOAN_MESSAGES { get; set; }
        public virtual DbSet<tbl_TUTT> tbl_TUTT { get; set; }
        public virtual DbSet<tbl_TUTT_JOB> tbl_TUTT_JOB { get; set; }
        public virtual DbSet<tbl_TUTT_PHI> tbl_TUTT_PHI { get; set; }
        public virtual DbSet<UNIT> UNITs { get; set; }
    }
}
