//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotations_Charges
    {
        public int ChargeID { get; set; }
        public string QuotationID { get; set; }
        public string ChargeName { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<double> rate { get; set; }
        public string Currency { get; set; }
        public string Notes { get; set; }
    
        public virtual Quotation Quotation { get; set; }
    }
}
