//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quotation()
        {
            this.Quotations_Charges = new HashSet<Quotations_Charges>();
        }
    
        public string QuotationID { get; set; }
        public string Qsatus { get; set; }
        public string Staff_ID { get; set; }
        public string contact { get; set; }
        public Nullable<System.DateTime> Qdate { get; set; }
        public string CusTo { get; set; }
        public string CusContact { get; set; }
        public Nullable<System.DateTime> Valid { get; set; }
        public string Term { get; set; }
        public string Vol { get; set; }
        public string Commodity { get; set; }
        public string POL { get; set; }
        public string ADDs { get; set; }
        public string POD { get; set; }
        public string Com_ID { get; set; }
    
        public virtual tbl_COM tbl_COM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotations_Charges> Quotations_Charges { get; set; }
    }
}
