//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LOG
    {
        public string ID { get; set; }
        public string Username { get; set; }
        public string WAN_IP { get; set; }
        public Nullable<System.DateTime> Login_time { get; set; }
        public Nullable<System.DateTime> Logout_time { get; set; }
    }
}
