//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TAI_KHOAN_MESSAGES
    {
        public int ID { get; set; }
        public System.Guid MessageID { get; set; }
        public string Username { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual tbl_MESSAGES tbl_MESSAGES { get; set; }
        public virtual tbl_TAI_KHOAN tbl_TAI_KHOAN { get; set; }
    }
}
