//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SCUSTOMER_RELATIONSHIP
    {
        public int ID { get; set; }
        public string SCustumer_ID { get; set; }
        public Nullable<System.DateTime> Cus_date { get; set; }
        public string Cus_satus { get; set; }
        public string Scheme { get; set; }
        public string Other { get; set; }
    
        public virtual tbl_SCUSTOMER tbl_SCUSTOMER { get; set; }
    }
}
