//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CUSTOMER()
        {
            this.tbl_HBL = new HashSet<tbl_HBL>();
        }
    
        public string Customer_ID { get; set; }
        public string Staff_ID { get; set; }
        public string Company_Name { get; set; }
        public string Company_Namekd { get; set; }
        public string Com_Address { get; set; }
        public string Com_Addresskd { get; set; }
        public string Website { get; set; }
        public string Duty_Person { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Com_DOB { get; set; }
        public string Bank_accountF { get; set; }
        public string bank_accountC { get; set; }
        public string Other { get; set; }
        public string Com_ID { get; set; }
    
        public virtual tbl_COM tbl_COM { get; set; }
        public virtual tbl_STAFF tbl_STAFF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HBL> tbl_HBL { get; set; }
    }
}
