//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_STAFF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_STAFF()
        {
            this.tbl_CUSTOMER = new HashSet<tbl_CUSTOMER>();
            this.tbl_HBL = new HashSet<tbl_HBL>();
            this.tbl_SCUSTOMER = new HashSet<tbl_SCUSTOMER>();
        }
    
        public string Staff_ID { get; set; }
        public string Department_ID { get; set; }
        public string Staff_name { get; set; }
        public string Nick_name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CitizenID { get; set; }
        public Nullable<System.DateTime> CitizenID_date { get; set; }
        public string CitizenID_place { get; set; }
        public Nullable<System.DateTime> StartingWokdDate { get; set; }
        public Nullable<float> Goal_target { get; set; }
        public string Position { get; set; }
        public string Bank_Account_No { get; set; }
        public string Bank_name { get; set; }
        public string Insurance_No { get; set; }
        public string Phone_No { get; set; }
        public string Passwords { get; set; }
        public string Com_ID { get; set; }
    
        public virtual tbl_COM tbl_COM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CUSTOMER> tbl_CUSTOMER { get; set; }
        public virtual tbl_DEPARTMENT tbl_DEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HBL> tbl_HBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SCUSTOMER> tbl_SCUSTOMER { get; set; }
    }
}
