//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HSCODE
    {
        public int ID { get; set; }
        public string HS_CODE { get; set; }
        public string Mo_ta_hang_hoaV { get; set; }
        public string Mo_ta_hang_hoaE { get; set; }
        public string Don_vi_tinh { get; set; }
        public string Xuat_xu { get; set; }
        public string Ma_bieu_mau_thue_NK { get; set; }
        public Nullable<double> Thue_NK_TT { get; set; }
        public Nullable<double> Thue_NK_UD { get; set; }
        public string Thue_VAT { get; set; }
        public Nullable<double> ACFTA { get; set; }
        public Nullable<double> ATIGA { get; set; }
        public Nullable<double> AJCEP { get; set; }
        public Nullable<double> VJEPA { get; set; }
        public Nullable<double> AKFTA { get; set; }
        public Nullable<double> AANZFTA { get; set; }
        public Nullable<double> AIFTA { get; set; }
        public Nullable<double> VKFTA { get; set; }
        public Nullable<double> VCFTA { get; set; }
        public Nullable<double> VN_EAEU { get; set; }
        public Nullable<double> CPTPP { get; set; }
        public Nullable<double> AHKFTA { get; set; }
        public Nullable<double> VNCU { get; set; }
        public Nullable<double> EVFTA { get; set; }
        public Nullable<double> UKVFTA { get; set; }
        public Nullable<double> VN_LAO { get; set; }
        public Nullable<double> RCEPT_A { get; set; }
        public Nullable<double> RCEPT_B { get; set; }
        public Nullable<double> RCEPT_C { get; set; }
        public Nullable<double> RCEPT_D { get; set; }
        public Nullable<double> RCEPT_E { get; set; }
        public Nullable<double> RCEPT_F { get; set; }
        public Nullable<double> TTDB { get; set; }
        public Nullable<double> XK { get; set; }
        public Nullable<double> XKCPTPP { get; set; }
        public Nullable<double> XKEV { get; set; }
        public Nullable<double> XKUKV { get; set; }
        public string Thue_BVMT { get; set; }
        public string Chinh_sach_hang_hoa { get; set; }
        public string Chinh_sach_hang_hoakd { get; set; }
        public string Mo_ta_hang_hoaVkd { get; set; }
        public string Loai_form { get; set; }
    }
}
