//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DELIVERYPFROOF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DELIVERYPFROOF()
        {
            this.tbl_DELIVERY_CONTH = new HashSet<tbl_DELIVERY_CONTH>();
        }
    
        public string Del_ID { get; set; }
        public Nullable<System.DateTime> Del_date { get; set; }
        public string HBL { get; set; }
        public string CNEE { get; set; }
        public string ADDs { get; set; }
        public string Place { get; set; }
        public string PersonInCharge { get; set; }
        public string TAX_ID { get; set; }
        public string TAX_CNEE { get; set; }
        public string TAX_ADDS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DELIVERY_CONTH> tbl_DELIVERY_CONTH { get; set; }
    }
}
