//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SUPPLIER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SUPPLIER()
        {
            this.tbl_INVOICE = new HashSet<tbl_INVOICE>();
            this.tbl_SUPPLIER_ACTION = new HashSet<tbl_SUPPLIER_ACTION>();
        }
    
        public string Supplier_ID { get; set; }
        public string Name_sup { get; set; }
        public string Typer { get; set; }
        public string Address_sup { get; set; }
        public string Bank_accountF { get; set; }
        public string Bank_accountC { get; set; }
        public string LCC_Fee { get; set; }
        public string Note { get; set; }
        public string Com_ID { get; set; }
    
        public virtual tbl_COM tbl_COM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_INVOICE> tbl_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SUPPLIER_ACTION> tbl_SUPPLIER_ACTION { get; set; }
    }
}
