//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SCUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SCUSTOMER()
        {
            this.tbl_SCUSTOMER_RELATIONSHIP = new HashSet<tbl_SCUSTOMER_RELATIONSHIP>();
        }
    
        public string SCustumer_ID { get; set; }
        public string Staff_ID { get; set; }
        public string Company_Name { get; set; }
        public string Com_address { get; set; }
        public string Website { get; set; }
        public string Duty_Person { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Com_DOB { get; set; }
        public string HCM_volume { get; set; }
        public string HP_volume { get; set; }
        public string DN_volume { get; set; }
        public string Other_volume { get; set; }
        public string Delivery_conditions { get; set; }
        public string Goods_type { get; set; }
        public string Good_name { get; set; }
        public string HS_code { get; set; }
        public string Foreign_port { get; set; }
        public string Import_country { get; set; }
        public string Export_country { get; set; }
        public string Term { get; set; }
        public string Payment_method { get; set; }
        public string Currency_code { get; set; }
        public string CK_export_name { get; set; }
        public string CK_export_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SCUSTOMER_RELATIONSHIP> tbl_SCUSTOMER_RELATIONSHIP { get; set; }
        public virtual tbl_STAFF tbl_STAFF { get; set; }
    }
}
