//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TAI_KHOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_TAI_KHOAN()
        {
            this.ChatMessages = new HashSet<ChatMessage>();
            this.tbl_TAI_KHOAN_MESSAGES = new HashSet<tbl_TAI_KHOAN_MESSAGES>();
        }
    
        public string Username { get; set; }
        public string Passwords { get; set; }
        public string FullName { get; set; }
        public string Statuss { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string Com_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatMessage> ChatMessages { get; set; }
        public virtual tbl_COM tbl_COM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TAI_KHOAN_MESSAGES> tbl_TAI_KHOAN_MESSAGES { get; set; }
    }
}
