//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DEPARTMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DEPARTMENT()
        {
            this.tbl_STAFF = new HashSet<tbl_STAFF>();
        }
    
        public string Department_ID { get; set; }
        public string Dep_name { get; set; }
        public string Other { get; set; }
        public string Note { get; set; }
        public string Com_ID { get; set; }
    
        public virtual tbl_COM tbl_COM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_STAFF> tbl_STAFF { get; set; }
    }
}
