//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_JOB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_JOB()
        {
            this.tbl_HBL = new HashSet<tbl_HBL>();
        }
    
        public string Request_ID { get; set; }
        public string Job_ID { get; set; }
        public string Goods_type { get; set; }
        public System.DateTime Job_date { get; set; }
        public string MBL { get; set; }
        public Nullable<System.DateTime> Issue_dateM { get; set; }
        public Nullable<System.DateTime> OnBoard_dateM { get; set; }
        public byte[] MBL_file { get; set; }
        public string ShipperM { get; set; }
        public string CNEEM { get; set; }
        public string Notify_PartyM { get; set; }
        public string Vessel_name { get; set; }
        public string Voyage_name { get; set; }
        public string POL { get; set; }
        public string POD { get; set; }
        public string PODel { get; set; }
        public string PODis { get; set; }
        public string PlaceofReceipt { get; set; }
        public string PlaceofDelivery { get; set; }
        public string Pre_Cariage_by { get; set; }
        public System.DateTime ETD { get; set; }
        public System.DateTime ETA { get; set; }
        public string Mode { get; set; }
        public string Agent { get; set; }
        public string Carrier { get; set; }
        public string Ycompany { get; set; }
        public string Link { get; set; }
        public Nullable<int> YunLock { get; set; }
        public Nullable<int> Use_time { get; set; }
        public string Com_ID { get; set; }
    
        public virtual AGENT AGENT1 { get; set; }
        public virtual CARRIER CARRIER1 { get; set; }
        public virtual tbl_COM tbl_COM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HBL> tbl_HBL { get; set; }
    }
}
