//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CHARGES
    {
        public int ID { get; set; }
        public string Debit_ID { get; set; }
        public Nullable<float> Exchange_rate { get; set; }
        public string Currency { get; set; }
        public string Ser_Name { get; set; }
        public Nullable<float> Ser_Price { get; set; }
        public Nullable<float> Ser_Quantity { get; set; }
        public string Ser_Unit { get; set; }
        public Nullable<float> Ser_VAT { get; set; }
        public Nullable<float> M_VAT { get; set; }
        public Nullable<bool> Buy { get; set; }
        public Nullable<bool> Sell { get; set; }
        public Nullable<bool> Paybehalf { get; set; }
        public Nullable<bool> Advance_payment { get; set; }
        public Nullable<bool> Refunds { get; set; }
        public Nullable<bool> Cont { get; set; }
        public Nullable<bool> Checked { get; set; }
    
        public virtual tbl_INVOICE tbl_INVOICE { get; set; }
    }
}
