//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CONTH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CONTH()
        {
            this.tbl_DELIVERY_CONTH = new HashSet<tbl_DELIVERY_CONTH>();
        }
    
        public int ID { get; set; }
        public string Cont_No { get; set; }
        public string HBL { get; set; }
        public Nullable<int> Cont_quantity { get; set; }
        public string Cont_type { get; set; }
        public string Seal_No { get; set; }
        public Nullable<double> Gross_weight { get; set; }
        public Nullable<double> CMB { get; set; }
        public string Goods_quantity { get; set; }
        public string Goods_depcription { get; set; }
    
        public virtual tbl_HBL tbl_HBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DELIVERY_CONTH> tbl_DELIVERY_CONTH { get; set; }
    }
}
