//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CNEE_ADD
    {
        public int ID { get; set; }
        public string Adds { get; set; }
        public string Place { get; set; }
        public string PersonInCharge { get; set; }
        public string CNEE { get; set; }
    
        public virtual tbl_CNEE tbl_CNEE { get; set; }
    }
}
