//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CNEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CNEE()
        {
            this.tbl_CNEE_ADD = new HashSet<tbl_CNEE_ADD>();
            this.tbl_HBL = new HashSet<tbl_HBL>();
        }
    
        public string CNEE { get; set; }
        public string VCNEE { get; set; }
        public string CAddress { get; set; }
        public string VAddress { get; set; }
        public string CCity { get; set; }
        public string CPerson_in_charge { get; set; }
        public string TaxID { get; set; }
        public string HAddress { get; set; }
        public string Com_ID { get; set; }
    
        public virtual tbl_COM tbl_COM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CNEE_ADD> tbl_CNEE_ADD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HBL> tbl_HBL { get; set; }
    }
}
