//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_INVOICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_INVOICE()
        {
            this.tbl_CHARGES = new HashSet<tbl_CHARGES>();
        }
    
        public string Debit_ID { get; set; }
        public string Invoice_type { get; set; }
        public Nullable<System.DateTime> Debit_date { get; set; }
        public Nullable<System.DateTime> Payment_date { get; set; }
        public string Invoice_No { get; set; }
        public Nullable<System.DateTime> Invoice_date { get; set; }
        public string Supplier_ID { get; set; }
        public string HBL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CHARGES> tbl_CHARGES { get; set; }
        public virtual tbl_HBL tbl_HBL { get; set; }
        public virtual tbl_SUPPLIER tbl_SUPPLIER { get; set; }
    }
}
