//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DELIVERY_CONTH
    {
        public string DC_ID { get; set; }
        public Nullable<int> ID { get; set; }
        public string Del_ID { get; set; }
    
        public virtual tbl_CONTH tbl_CONTH { get; set; }
        public virtual tbl_DELIVERYPFROOF tbl_DELIVERYPFROOF { get; set; }
    }
}
