//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TUTT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_TUTT()
        {
            this.tbl_TUTT_JOB = new HashSet<tbl_TUTT_JOB>();
            this.tbl_TUTT_PHI = new HashSet<tbl_TUTT_PHI>();
        }
    
        public string SoTUTT { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string NhanvienTUTT { get; set; }
        public string Noi_dung { get; set; }
        public Nullable<bool> Thuong { get; set; }
        public Nullable<bool> da { get; set; }
        public Nullable<bool> ketoan { get; set; }
        public Nullable<bool> ceo { get; set; }
        public string Ghi_chu { get; set; }
        public string Com_ID { get; set; }
    
        public virtual tbl_COM tbl_COM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TUTT_JOB> tbl_TUTT_JOB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TUTT_PHI> tbl_TUTT_PHI { get; set; }
    }
}
