//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TUTT_PHI
    {
        public int ID { get; set; }
        public string SoHoaDon { get; set; }
        public string TenPhi { get; set; }
        public Nullable<bool> TU { get; set; }
        public Nullable<bool> TT { get; set; }
        public Nullable<double> SoTien { get; set; }
        public string NghiChu { get; set; }
        public string SoTUTT { get; set; }
    
        public virtual tbl_TUTT tbl_TUTT { get; set; }
    }
}
